name: Basic verify

on:
  pull_request:
    branches: 
      - "main"
      - "RN"
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  compile-check:
    runs-on: windows-2022
    env:
      CONFIGURATION: FinalAlertDebug YR

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
        lfs: true
    - name: setup-msvc
      uses: egor-tensin/vs-shell@v2
      with:
        # Target architecture
        arch: x64
    - name: Restore cache vcpkg
      uses: actions/cache/restore@v4
      with:
        path: |
          3rdParty/xcc/vcpkg_downloads
          3rdParty/xcc/vcpkg_installed
          C:/Users/runneradmin/AppData/Local/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
    - name: Build Main Program (MSVC)
      run: |
        devenv.com "MissionEditor.sln"  /Build "${{ env.CONFIGURATION }}|x64" /project MissionEditor
    - name: Build UT tool (MSVC)
      run: |
        devenv.com "MissionEditor.sln"  /Build "${{ env.CONFIGURATION }}|x64" /project UnitTest
    - name: Cache vcpkg
      uses: actions/cache/save@v4
      with:
        path: |
          3rdParty/xcc/vcpkg_downloads
          3rdParty/xcc/vcpkg_installed
          C:/Users/runneradmin/AppData/Local/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
    - name: do UT
      run: |
        cd x64\Debug
        ./UnitTest
    - name: Make file name
      shell: bash
      run: |
        pkgName="RN-Mission-Editor-pr-${{ github.run_number }}.zip"
        echo "PACKAGE_NAME=$pkgName" >> $GITHUB_ENV
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: dist/FinalAlert2YR